fix: remove StdStorage in CommonBase contract
foundry-rs/forge-std pull request #241
Opened 2022-11-27 08:31 UTC by graykode

Remove `StdStorage` in [Common.sol](https://github.com/foundry-rs/forge-std/blob/master/src/Common.sol)
If there is `StdStorage` in Common.sol, this testcase cant return ERROR when run with forge

```solidity
pragma solidity ^0.8.0;

import "forge-std/Test.sol";

contract good is Test {
    uint256 a;

    function testAAA() public {
        uint256 id = vm.snapshot();
        a = 1;
        assertEq(a, uint256(2));
        vm.revertTo(id);
    }
}
```

2022-11-28 01:44 UTC, mds1 commented
Holding off on merging this per discussion in https://github.com/foundry-rs/foundry/issues/3055 — let's move discussion there, cc @ZeroEkkusu if you have any thoughts on this PR

2022-11-29 14:21 UTC, ZeroEkkusu requested changes
Initializing a `struct` before `DSTest` is inherited causes the example to pass.

Since it's a false positive (dangerous), let's fix the issue immediately. @graykode, could you please move `TestBase` to the of the inheritance chain instead:

```solidity
abstract contract Test is DSTest, StdAssertions, StdCheats, StdUtils, TestBase {}
```

2022-11-29 15:02 UTC, mattsse approved these changes
agree, let's merge and I'll debug the root cause.

@mds1 probably need another patch release?

2022-11-30 17:42 UTC, mds1 commented
@ZeroEkkusu I pushed the required changes and verified the test now reverts as expected. Feel free to review/merge

2022-11-30 19:22 UTC, ZeroEkkusu approved these changes

2022-11-30 19:23 UTC, merged